name: icon_broken
description: A package that helps you add more icons
version: 0.0.1
repository: https://github.com/HanySameh/IconBroakenPackage

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf


  